"""add Exam, Question, Attempt, AttemptAnswer

Revision ID: 75d110b216f3
Revises: 886f2ca30ae8
Create Date: 2025-08-15 13:19:56.521546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d110b216f3'
down_revision = '886f2ca30ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('raw', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_user_id'), ['user_id'], unique=False)

    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('choice_a', sa.Text(), nullable=False),
    sa.Column('choice_b', sa.Text(), nullable=False),
    sa.Column('choice_c', sa.Text(), nullable=False),
    sa.Column('choice_d', sa.Text(), nullable=False),
    sa.Column('correct', sa.String(length=1), nullable=False),
    sa.CheckConstraint("correct in ('A','B','C','D')", name='ck_question_correct_is_valid_choice'),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_exam_id'), ['exam_id'], unique=False)

    op.create_table('attempt_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected', sa.String(length=1), nullable=False),
    sa.CheckConstraint("selected in ('A','B','C','D')", name='ck_attempt_answer_selected_is_valid_choice'),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_attempt_answer_attempt_question')
    )
    with op.batch_alter_table('attempt_answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_answer_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_answer_question_id'), ['question_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('attempt_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_answer_question_id'))
        batch_op.drop_index(batch_op.f('ix_attempt_answer_attempt_id'))

    op.drop_table('attempt_answer')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_exam_id'))

    op.drop_table('question')
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_user_id'))
        batch_op.drop_index(batch_op.f('ix_attempt_exam_id'))

    op.drop_table('attempt')
    op.drop_table('exam')
    # ### end Alembic commands ###
